export { Header } from './Header';
export { Presentation } from './Presentation';
export { AboutUs } from './AboutUs';
export { HowItWorks } from './HowItWorks';
export { Discovery } from './Discovery';
export { Price } from './Price';
export { Feedback } from './Feedback';
export { Doubts } from './Doubts';
export { Footer } from './Footer';
